import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Form from '@/components/Form'
import Footer from '@/components/Footer'
import Link from 'next/link'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className={`${styles.main}`}>
        <div className={`${styles.top}`}>
        <div className={`${styles.leftSide}`}>
          <Image src={'/images/phone.png'} alt="phone images" width={450} height={700}/>
        </div>
        <div className={`${styles.rightSide}`}>
          <Form/>
          <h2>Don't have an account? <Link href="https://www.instagram.com/accounts/emailsignup/" className={`${styles.signup}`}>Sign up</Link>
          </h2>
          <p>Get the app.</p>
          <div className={`${styles.appLinks}`}>
            <Link href="https://play.google.com/" >
            <Image src={'/images/google-play.png'} alt="google play logo" width={130} height={40}/>
            </Link>
            <Link href="https://apps.microsoft.com/" >
            <Image src={'/images/microsoft.png'} alt="microsoft logo" width={130} height={40}/>
            </Link>
          </div>
        </div>
        </div>
        <Footer/>
      </main>
    </>
  )
}
